<?php

namespace Database\Seeders;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $Product = [
            [
                'id'                    => 1,
                'name'                  => 'project 1',
                'secret_key'            => 'vme4rzrm5zmv4py796w8c7ddwqczv88f',
                'product_key'           => '96w8c7ddwqczv88f',
                'status'                => 0,
                'description'           => '1',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 1,
                'currency_id'          => 1,
                'gate_id'              => '1',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 2,
                'name'                  => 'project 2',
                'secret_key'            => 'U6cvkayjXdOoMNYOou8006vj7XQFkUXq',
                'product_key'           => '1Y760jjRupWCbf2Q',
                'status'                => 0,
                'description'           => '2',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 1,
                'currency_id'          => 1,
                'gate_id'              => '2',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 3,
                'name'                  => 'project 3',
                'secret_key'            => 'VxQ2QxhOOR00rf2DXly5GSpDoPzpS5Tj',
                'product_key'           => 'ONWqgO4hJ2smw9Me',
                'status'                => 0,
                'description'           => '3',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 1,
                'currency_id'          => 1,
                'gate_id'              => '3',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 4,
                'name'                  => 'project 4',
                'secret_key'            => 'KLV4qZS76bbCEZjgTMzGyqO8VtOFzGjQ',
                'product_key'           => 'nRxgaPfSp8mpJytn',
                'status'                => 0,
                'description'           => '4',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 2,
                'currency_id'          => 1,
                'gate_id'              => '4',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 5,
                'name'                  => 'project 5',
                'secret_key'            => 'YUOLQyWP58TVbYmTelE76CncEO9cAKB7',
                'product_key'           => 'pC7dp9QrJbjveFMw',
                'status'                => 0,
                'description'           => '5',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 3,
                'currency_id'          => 1,
                'gate_id'              => '5',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 6,
                'name'                  => 'project 6',
                'secret_key'            => 'rBnQOqCYGuu3J15aTrkMI9BgpgR2iYXA',
                'product_key'           => 'wmyLBRxsEObd1QIB',
                'status'                => 0,
                'description'           => '6',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'           => 3,
                'currency_id'           => 1,
                'gate_id'               => '6',
                'processing_fee'        => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 7,
                'name'                  => 'project 7',
                'secret_key'            => '0Pl8g9E0adWELqdAlhoZX2CnOXviU45N',
                'product_key'           => 'KDpwT9KklYChIj9V',
                'status'                => 0,
                'description'           => '7',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 4,
                'currency_id'          => 1,
                'gate_id'              => '7',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 8,
                'name'                  => 'project 8',
                'secret_key'            => '2jPUCZkkFlGFvDIbrW6COA83pyaZAbfw',
                'product_key'           => 'INYMmxmF3RC5x6VT',
                'status'                => 0,
                'description'           => '8',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 4,
                'currency_id'          => 1,
                'gate_id'              => '8',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 9,
                'name'                  => 'project 9',
                'secret_key'            => 'ZclGR9qdcu8N5aFF4QS1AuZ6mzEVdt8Y',
                'product_key'           => 'EOeiUbud2GE0npt1',
                'status'                => 0,
                'description'           => '9',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 5,
                'currency_id'          => 1,
                'gate_id'              => '9',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
            [
                'id'                    => 10,
                'name'                  => 'project 10',
                'secret_key'            => 'vZHkgu6eyjJuXxZpUclO8TOd8qDVR7R2',
                'product_key'           => 'u64QSdIJnJqe3z2t',
                'status'                => 0,
                'description'           => '10',
                'callback_url'          => 'null',
                'redirect_url'          => 'null',
                'created_at'            => now(),
                'updated_at'            => now(),
                'deleted_at'            => null,
                'merchant_id'          => 5,
                'currency_id'          => 1,
                'gate_id'              => '10',
                'processing_fee'       => '{"deposit":[{"rate":"1","fix":"1"}],"settlement":[{"rate":"1","fix":"1"}],"payout":[{"rate":"1","fix":"1"}],"top_up":[{"rate":"1","fix":"1"}],"top_up_merchant":[{"rate":"0","fix":"0"}],"payout_merchant":[{"rate":"0","fix":"0"}]}',
                'current_credit'        => 1000,
                'freeze_credit'         => 0,
            ],
        ];

        Product::insert($Product);
    }
}
