FORMAT: 1A

# PG API

Before you integrate PG into your application, you should have done the registration 
and having the encryption keys. The 2 encryption key is for production environment. 
Please ensure your callback URL is valid and updated in PG portal.

## Make REST API call

In REST API calls, include the URL to the API service for the environment:
 
*Production*: https://pg.techworlds.com.my

Also, encrypt your data parameter with the encryption key we provided to prove your identity and access protected resources.

# Group Encryption & Decryption

To secure the communication, besides whitelisting IP address, PG implements encryption by 
using generated product key and secret key to encrypt your request parameters. Therefore, 
the encrypted data will be validated by PG vice versa. If the keys are valid, then it will 
be considered genuine request or response. You may contact us to regenerate your encryption 
keys if needed.
<br/><br/>
> **NOTE**: *Please keep your secret key and product key confidentiality.*

<br/><br/>
The PG will generate 32-character length of secretKey and 16-character length of productKey.
<br/><br/>
`secretKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
<br/><br/>
`productKey: xxxxxxxxxxxxxxxx`

    

# Group API Request

To make a REST API request, you combine the HTTP `GET` and `POST` method, the URL to the API service.

The URL to the API service is either:

*Production*: https://pg.techworlds.com.my

Most `GET` and `POST` calls require a JSON request body.
<br/><br/><br/>
**HTTP request headers**

The commonly used HTTP request headers are:

**Accept**

    The response format, which is required for operations with a response body. The syntax is:

                Accept: application/json

<br/><br/>
**Content Type**

    The request format, which is required for operations with a request body. The syntax is:

                Content-Type: application/json

# Group API Responses

PG API calls return HTTP status codes. Some API calls also return JSON response bodies that 
include information about the resources. Each REST API request returns an HTTP status code.
<br/><br/><br/>
**HTTP status code**

For successful requests, PG returns HTTP `2xx` status codes.

For failed requests, PG returns HTTP `4xx` or `5xx` status codes.

PG may returns these HTTP status codes:

Status code | Description
---|---
`200 OK`  |   The request succeeded.
`201 Created`  |   A `POST` method successfully created a resource. If the resource was already created by a previous execution of the same method
`400 Bad Request`  |   `INVALID_REQUEST`. Request is not well-formed, syntactically incorrect, or violates schema.
`401 Unauthorized`  |   `AUTHENTICATION_FAILURE`. Authentication failed due to invalid authentication credentials.
`403 Forbidden`  |   `NOT_AUTHORIZED`. Authorization failed due to insufficient permissions.
`404 Not Found`  |   `RESOURCE_NOT_FOUND`. The specified resource does not exist.
`405 Method Not Allowed`  |   `METHOD_NOT_SUPPORTED`. The server does not implement the   requested HTTP method.
`500 Internal Server Error`  |   `INTERNAL_SERVER_ERROR`. An internal server error has occurred.
`503 Service Unavailable`  |   `SERVICE_UNAVAILABLE`. Service Unavailable.

<br/><br/>
**API error code**
Status code | Description
---|---
`422`  |   form validate error (ret_msg with show detail)
`5000`  |   too many attempt in 1 min
`9000`  |   ip not in white list

# Group Deposit

#### Parameters [POST /api/v1/top-ups/user]

**API error code**
Status code | Description
---|---
`10000` |  invalid Gate
`10001` |  secret key && product key error
`10002` |  current gate is no found an currency
`10003` |  no found valid PG Saving account
`10004` |  occur error when insert into database (pls contact customer service)
`10005` |  empty secret key
`10006` |  empty product key
`10007` | empty form data
`10008` |  decode data false
`10009` |  invalid top up form
`10010` |  top up res is expired
`10011` |  occur error when update into database (pls contact customer service)
`10012` |  repeat submit payment page
`10013` |  image is not valid (size / mime type / s3 server problem)

<br/><br/>
Parameters that need to be pass for the request.

Parameters | Type | Required | Description
---|---|---|---
redirect_url  |  string | no | Redirect URL
client_transaction  |  string | yes | Client transaction ID
gate_id | string | yes | Project ID.
product_key | string | yes | Product key generate by PG
secret_key | string | yes | Secret key generate by PG
amount | string | yes | Deposit amount

+ Parameters
    - redirect_url : `https://www.example.com/` (string, optional) - Redirect URL
    - client_transaction : `1` (string, required) - Generated client transaction ID
    - gate_id : `9` (string, required) - Gate ID
    - product_key : `abcd1234abcd1234` (string, required) - Product key generate by PG
    - secret_key : `abcd1234abcd1234abcd1234abcd1234` (string, required) - Secret key generate by PG
    - amount : `10000` (decimal, required) - Amount

+ Response 200 (application/json)

        {
            "status": 0,
            "ret_msg": "Success",
            "data": {
                "call_back_url": "http:\/\/pgpay.techworlds.com.my\/#topup\/?signature|..."
        }
        
# Group Payout 

#### Parameters [POST /api/v1/payout/user]

**API error code**
Status code | Description
---|---
`10050` |  secret key && product key verify error
`10051` |  occur error when create payout (pls contact customer service)
`10052` |  invalid Gate
<br/><br/>
Parameters that need to be pass for the request.

Parameters | Type | Required | Description
---|---|---|---
gate_id  |   string | yes | Project ID
product_key | string | yes | Product key generate by PG
secret_key | string | yes | Secret key generate by PG
bank_name  |   string | yes | User bank name
bank_account_name | string | yes | User bank account name
bank_account_number  |   string | yes | User bank account number
amount | string | yes | Payout amount
remark | string | no | Remark

+ Parameters
    - gate_id : `1` (string, required) - Gate ID
    - product_key : `abcd1234abcd1234` (string, required) - Product key generate by PG
    - secret_key : `abcd1234abcd1234abcd1234abcd1234` (string, required) - Secret key generate by PG
    - bank_name : `test` (string, required) - Bank name
    - bank_account_name : `test` (string, required) - Bank account name
    - bank_account_number : `999` (string, required) - Bank account number
    - amount : `10000` (decimal, required) - Amount
    - remark : `test` (string, optional) - Remark

+ Response 200 (application/json)

        {
            "status": 0,
            "ret_msg": "Success",
            "data":[
            ]
        }
        
# Group Wallet 

#### Parameters [POST /api/v1/wallet]

<br/><br/>
Parameters that need to be pass for the request.

Parameters | Type | Required | Description
---|---|---|---
gate_id  |   string | yes | Project ID
product_key | string | yes | Product key generate by PG
secret_key | string | yes | Secret key generate by PG

+ Parameters
    - gate_id : `1` (string, required) - Gate ID
    - product_key : `abcd1234abcd1234` (string, required) - Product key generate by PG
    - secret_key : `abcd1234abcd1234abcd1234abcd1234` (string, required) - Secret key generate by PG

+ Response 200 (application/json)

        {
            "status": 0,
            "ret_msg": "Success",
            "data":[
                {
                    "id":3,
                    "amount":"123.00",
                    "bank_name":"123",
                    "bank_account_name":"123",
                    "bank_account_number":"123",
                    "remark":"123",
                    "document_no":"p210317121237003",
                    "created_at":"2021-03-17 12:12:37",
                    "admin_remark":null,
                    "processing_fee":"2.23",
                    "processing_rate":"1.00",
                    "processing_fix":"1.00",
                }
            ]
        }